from appium import webdriver



des_cap = {

    "deviceName": "Android Emulator",
    "platformName": "Android",
    "appPackage": "com.veronicaapps.veronica.simplecalculator",
    "appWaitActivity": "com.veronicaapps.veronica.simplecalculator.MainActivity",
    "automationName": "UiAutomator2",
    "app": "/Users/mac/Library/Android/sdk/build-tools/30.0.3/Simple Calculator_v1.9_apkpure.com.apk"
}
driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub", des_cap)
el1 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_seven")
el1.click()
el2 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_four")
el2.click()
el3 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_plus")
el3.click()
el4 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_eight")
el4.click()
el5 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_nine")
el5.click()
el6 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el6.click()
el7 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_five")
el7.click()
el8 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_six")
el8.click()
el9 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_minus")
el9.click()
el10 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_one")
el10.click()
el11 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_two")
el11.click()
el12 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el12.click()
el13 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_three")
el13.click()
el14 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_zero")
el14.click()
el15 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_divide")
el15.click()
el16 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_two")
el16.click()
el17 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el17.click()
el17.click()
el18 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_two")
el18.click()
el19 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_one")
el19.click()
el20 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_multiply")
el20.click()
el21 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_zero")
el21.click()
el22 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_point")
el22.click()
el23 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_three")
el23.click()
el24 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_six")
el24.click()
el25 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el25.click()
el26 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_six")
el26.click()
el27 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_five")
el27.click()
el28 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_percent")
el28.click()
el29 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el29.click()
el30 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_three")
el30.click()
el31 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_sign")
el31.click()
el32 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_one")
el32.click()
el33 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_plus")
el33.click()
el34 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_six")
el34.click()
el35 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_sign")
el35.click()
el36 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_zero")
el36.click()
el37 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el37.click()
el38 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_nine")
el38.click()
el39 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_five")
el39.click()
el40 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_cancel")
el40.click()
el41 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_nine")
el41.click()
el42 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_equals")
el42.click()
el43 = driver.find_element_by_id("com.veronicaapps.veronica.simplecalculator:id/button_backspace")
el43.click()



